Create README.fa.md
microsoft/Data-Science-For-Beginners pull request #241
Opened 2021-11-01 07:47 UTC by vahidbaghi

adding persian translation

2021-11-02 22:17 UTC, paladique requested changes
Thank you for your contribution @vahidbaghi just a few broken link fixes and this will be ready to merge 🎉

2021-11-02 22:17 UTC, paladique commented on 1-Introduction/translations/README.fa.md
> +![data in action](images/data.jpg)
this image is currently broken as is as the README file is in a subdirectory, so be sure to update the path

2021-11-02 22:17 UTC, paladique commented on 1-Introduction/translations/README.fa.md
> +1. [تعریف علم داده](01-defining-data-science/README.md)
these 4 links are outside of the translations folder and should be updated to the English version path (until we get more Farsi translations 🙂 )

2021-11-05 06:58 UTC, vahidbaghi commented on 1-Introduction/translations/README.fa.md
> +1. [تعریف علم داده](01-defining-data-science/README.md)
I will translate all the texts into Persian soon.

2021-11-08 16:24 UTC, paladique approved these changes

2021-11-08 16:24 UTC, merged